#!/bin/bash

red=$'\e[0;31m'
reset=$'\e[0m'
green=$'\e[0;32m'

function green {
  echo $green$1 $reset
}

function red {
  echo $red$1 $reset
}

function say_ok {
  green '✔'
}

function say_fail {
  red '✘'
}
